version: "3.8"
services:

  # application
  web:
    image: tripster_web
    container_name: "tripster_web"
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/app/migrations/versions:/tripster/src/app/migrations/versions
    links:
      - postgresql

  # database
  postgresql:
    container_name: "tripster_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tripster
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
